# Generated by Django 5.1.3 on 2026-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_signvideo_translationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='matched_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
